import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import axios from 'axios'
import { Cursor } from 'mongoose'
export default function Home() {
  type User = {
    name: string
    age: string
  }
  const [info, seInfo] = useState<User[]>([])

  const [formData, setFormData] = useState<User>({
    name: '',
    age: '',
  })

  const handleClick = async  () => {
    const user = formData;
    setFormData({
      name : '',
      age : '',
    })
    await axios.post('http://localhost:3000/api/users', user)
    .then(res => {
     seInfo(res.data)
      
    })
    .catch(err => {
      console.log(err)
    })
    

  }

  const deleteUser = async(username : string)=>{
    await axios.delete(`http://localhost:3000/api/users/${username}`)
    .then(res => {
     seInfo(res.data)
      
    })
    .catch(err => {
      console.log(err)
    })

  }

  const getData = async () => {
    console.log('getting data')
   axios.get('http://localhost:3000/api/users')
    .then(res => {
      seInfo(res.data)
    })
    .catch(err => {
      console.log(err)
    })


  }

  useEffect(() => {
    //fetch all data using fetch api
    getData()

  }, [])




  return (
    <>
      <Head>
        <title>Next Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

      </Head>
      <main >
        <div className="d-flex container mt-5 justify-content-evenly">
        
        <div>
          {
            info.map((item, index) => {
              return (
                <div key={index} className="border border-primary rounded p-3 mb-3 " style={{
                  cursor: 'pointer'
                }}>
                  <h1 className="text-uppercase text-primary" onClick={()=>{
                    deleteUser(item.name)
                  }}>{item.name}</h1>
                  <p className="fs-1 fw-bold">{item.age}</p>
                </div>
              )
            })
          }
        </div>
        <div className="">
          <h1 className="text-primary text-center text-uppercase mb-4">Add  User</h1>
          <input className="form-control mb-4" type="text" placeholder="name" value={formData.name} onChange={(e) => setFormData({ ...formData, name: e.target.value })} />
          <input className="form-control mb-4" type="text" placeholder="age" value={formData.age} onChange={(e) => setFormData({ ...formData, age: e.target.value })} />
          <button className="btn btn-primary w-100 " onClick={handleClick}>Submit</button>
        </div>
        </div>

      </main>
    </>
  )
}
